SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Country`;
DROP TABLE IF EXISTS `Business`;
DROP TABLE IF EXISTS `PaymentInfo`;
DROP TABLE IF EXISTS `Payment`;
DROP TABLE IF EXISTS `Performance`;
DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `ProductPhoto`;
DROP TABLE IF EXISTS `Process`;

SET FOREIGN_KEY_CHECKS = 1;
